## Projet SQL : Préparer les données pour SQLite

## Découverte du dataset

In [1]:
import pandas as pd
import sqlite3

# Affichage du dataframe
df = pd.read_csv('academy_awards.csv', encoding='ISO-8859-1')

In [2]:
# Afficher les 5 premiéres lignes
df.head()

,Year,Category,Nominee,Additional Info,Won?,Unnamed: 5,Unnamed: 6,Unnamed: 7,Unnamed: 8,Unnamed: 9,Unnamed: 10
0,2010 (83rd),Actor -- Leading Role,Javier Bardem,Biutiful {'Uxbal'},NO,NaN,NaN,NaN,NaN,NaN,NaN
1,2010 (83rd),Actor -- Leading Role,Jeff Bridges,True Grit {'Rooster Cogburn'},NO,NaN,NaN,NaN,NaN,NaN,NaN
2,2010 (83rd),Actor -- Leading Role,Jesse Eisenberg,The Social Network {'Mark Zuckerberg'},NO,NaN,NaN,NaN,NaN,NaN,NaN
3,2010 (83rd),Actor -- Leading Role,Colin Firth,The King's Speech {'King George VI'},YES,NaN,NaN,NaN,NaN,NaN,NaN
4,2010 (83rd),Actor -- Leading Role,James Franco,127 Hours {'Aron Ralston'},NO,NaN,NaN,NaN,NaN,NaN,NaN

In [3]:
# Utiliser la fonction value_counts de la librairie python pour voir si il y a des données intéréssantes dans ces colonnes sans noms

In [4]:
df['Unnamed: 5'].value_counts()

Unnamed: 5
*                                                                                                               7
 resilience                                                                                                     1
 D.B. "Don" Keele and Mark E. Engebretson has resulted in the over 20-year dominance of constant-directivity    1
 error-prone measurements on sets. [Digital Imaging Technology]"                                                1
 discoverer of stars                                                                                            1
Name: count, dtype: int64

In [5]:
df['Unnamed: 6'].value_counts()

Unnamed: 6
*                                                                   9
 flexibility and water resistance                                   1
 direct radiator bass style cinema loudspeaker systems. [Sound]"    1
 sympathetic                                                        1
Name: count, dtype: int64

In [6]:
df['Unnamed: 7'].value_counts()

Unnamed: 7
 while requiring no dangerous solvents. [Systems]"    1
*                                                     1
 kindly                                               1
Name: count, dtype: int64

In [7]:
# On remarque donc que les colonnes sans noms sont sans importance donc on peut désormais les supprimés par la suite

In [8]:
# Afficher le nombre de lignes et de colonnes du dataset
df.shape

(10137, 11)

## Filtrer les données

In [9]:
df['Year'].value_counts()

Year
1941 (14th)      192
1942 (15th)      190
1943 (16th)      188
1944 (17th)      181
1945 (18th)      163
                ...
1930/31 (4th)     50
1931/32 (5th)     47
1929/30 (3rd)     42
1927/28 (1st)     39
1928/29 (2nd)     38
Name: count, Length: 83, dtype: int64

In [10]:
# On garde seulement les 4 premiers caractères de la colonne 'Year'

In [11]:
df['Year'] = df['Year'].str[0:4]

In [12]:
# On vérifie le type de la colonne 'Year'

In [13]:
df['Year'].dtypes

dtype('O')

In [14]:
# Conversion de la colonne 'Year' de texte (string) vers un entier (int)

In [15]:
df['Year'] = df['Year'].astype(int)

In [16]:
# Vérifier à nouveau que la colonne 'Year' est bien un nombre entier

In [17]:
df['Year'].dtypes

dtype('int64')

In [18]:
# Filtrer et garder les années aprés 2000 de la colonne 'Year'
later_than_2000 = df[df['Year'] > 2000]

In [19]:
# Affichage de quelques valeurs
later_than_2000.head()

,Year,Category,Nominee,Additional Info,Won?,Unnamed: 5,Unnamed: 6,Unnamed: 7,Unnamed: 8,Unnamed: 9,Unnamed: 10
0,2010,Actor -- Leading Role,Javier Bardem,Biutiful {'Uxbal'},NO,NaN,NaN,NaN,NaN,NaN,NaN
1,2010,Actor -- Leading Role,Jeff Bridges,True Grit {'Rooster Cogburn'},NO,NaN,NaN,NaN,NaN,NaN,NaN
2,2010,Actor -- Leading Role,Jesse Eisenberg,The Social Network {'Mark Zuckerberg'},NO,NaN,NaN,NaN,NaN,NaN,NaN
3,2010,Actor -- Leading Role,Colin Firth,The King's Speech {'King George VI'},YES,NaN,NaN,NaN,NaN,NaN,NaN
4,2010,Actor -- Leading Role,James Franco,127 Hours {'Aron Ralston'},NO,NaN,NaN,NaN,NaN,NaN,NaN

In [20]:
# Regarder combien de valeurs ont a désormais sur notre dataframe
later_than_2000.shape

(1294, 11)

In [21]:
# Actor -- Leading Role
# Actor -- Supporting Role
# Actress -- Leading Role
# Actress -- Supporting Role

# Création d'une liste qui contient ces 4 catégories
award_categories = ['Actor -- Leading Role', 'Actor -- Supporting Role', 
                    'Actress -- Leading Role', 'Actress -- Supporting Role']

In [22]:
# Filtrer et garder uniquement les lignes qui contiennent ces 4 catégories avec la méthode 'ISIN' sur le dataset later_than_2000
nominations = later_than_2000[later_than_2000['Category'].isin(award_categories)].copy()

In [23]:
# Vérifier le nombre de lignes et de colonnes
nominations.shape

(200, 11)

In [24]:
# Afficher quelques lignes (pour vérifier)
nominations.head()

,Year,Category,Nominee,Additional Info,Won?,Unnamed: 5,Unnamed: 6,Unnamed: 7,Unnamed: 8,Unnamed: 9,Unnamed: 10
0,2010,Actor -- Leading Role,Javier Bardem,Biutiful {'Uxbal'},NO,NaN,NaN,NaN,NaN,NaN,NaN
1,2010,Actor -- Leading Role,Jeff Bridges,True Grit {'Rooster Cogburn'},NO,NaN,NaN,NaN,NaN,NaN,NaN
2,2010,Actor -- Leading Role,Jesse Eisenberg,The Social Network {'Mark Zuckerberg'},NO,NaN,NaN,NaN,NaN,NaN,NaN
3,2010,Actor -- Leading Role,Colin Firth,The King's Speech {'King George VI'},YES,NaN,NaN,NaN,NaN,NaN,NaN
4,2010,Actor -- Leading Role,James Franco,127 Hours {'Aron Ralston'},NO,NaN,NaN,NaN,NaN,NaN,NaN

## Nettoyer les colonnes Unnamed et Won

In [25]:
# Création d'un dictionnaire de remplacement afin de remplacer les NO = 0 et Yes = 1
replacements = {"NO":0, "YES":1}

In [26]:
nominations['Won?'] = nominations['Won?'].map(replacements)

In [27]:
nominations["Won"] = nominations["Won?"]

In [28]:
nominations.head()

,Year,Category,Nominee,Additional Info,Won?,Unnamed: 5,Unnamed: 6,Unnamed: 7,Unnamed: 8,Unnamed: 9,Unnamed: 10,Won
0,2010,Actor -- Leading Role,Javier Bardem,Biutiful {'Uxbal'},0,NaN,NaN,NaN,NaN,NaN,NaN,0
1,2010,Actor -- Leading Role,Jeff Bridges,True Grit {'Rooster Cogburn'},0,NaN,NaN,NaN,NaN,NaN,NaN,0
2,2010,Actor -- Leading Role,Jesse Eisenberg,The Social Network {'Mark Zuckerberg'},0,NaN,NaN,NaN,NaN,NaN,NaN,0
3,2010,Actor -- Leading Role,Colin Firth,The King's Speech {'King George VI'},1,NaN,NaN,NaN,NaN,NaN,NaN,1
4,2010,Actor -- Leading Role,James Franco,127 Hours {'Aron Ralston'},0,NaN,NaN,NaN,NaN,NaN,NaN,0

In [29]:
# Supprimer les colonnes inutiles
drop_cols = ["Won?", "Unnamed: 5", "Unnamed: 6", "Unnamed: 7", "Unnamed: 8", "Unnamed: 9", "Unnamed: 10"]

In [30]:
# Supprimant les colonnes de 'drop_cols'
final_nominations = nominations.drop(drop_cols, axis=1)

In [31]:
# Vérifier que tout est Ok 
final_nominations.head()

,Year,Category,Nominee,Additional Info,Won
0,2010,Actor -- Leading Role,Javier Bardem,Biutiful {'Uxbal'},0
1,2010,Actor -- Leading Role,Jeff Bridges,True Grit {'Rooster Cogburn'},0
2,2010,Actor -- Leading Role,Jesse Eisenberg,The Social Network {'Mark Zuckerberg'},0
3,2010,Actor -- Leading Role,Colin Firth,The King's Speech {'King George VI'},1
4,2010,Actor -- Leading Role,James Franco,127 Hours {'Aron Ralston'},0

In [32]:
# On peut voir désormais que la colonne 'WON?' et les autres colonnes 'Unnamed' ont été supprimés

## Nettoyage de la colonne Additionnal Info

In [33]:
# On va séparer le nom du film, ainsi que l'acteur à partir de notre tableau final_nominations
# FILM {'PERSONNAGE'}

# Ensuite on va créer un tableau séparant les deux infos
# Biutiful {'Uxbal'}
# The Social Network --> Mark Zuckerberg

In [34]:
additional_info_one = final_nominations['Additional Info'].str.rstrip("'}")

In [35]:
additional_info_one.head()

0                        Biutiful {'Uxbal
1             True Grit {'Rooster Cogburn
2    The Social Network {'Mark Zuckerberg
3      The King's Speech {'King George VI
4                127 Hours {'Aron Ralston
Name: Additional Info, dtype: object

In [36]:
additional_info_two = additional_info_one.str.split(" {'", expand=True)

In [37]:
additional_info_two.head()

                    0                1
0            Biutiful            Uxbal
1           True Grit  Rooster Cogburn
2  The Social Network  Mark Zuckerberg
3   The King's Speech   King George VI
4           127 Hours     Aron Ralston

In [38]:
# Enregistrer dans une nouvelle variable = les films 
movie_names = additional_info_two[0]

In [39]:
movie_names.head()

0              Biutiful
1             True Grit
2    The Social Network
3     The King's Speech
4             127 Hours
Name: 0, dtype: object

In [40]:
# Enregistrer dans une nouvelle variable = les personnages 
characters = additional_info_two[1]

In [41]:
characters.head()

0              Uxbal
1    Rooster Cogburn
2    Mark Zuckerberg
3     King George VI
4       Aron Ralston
Name: 1, dtype: object

In [42]:
# Ajouter ses deux colonnes dans notre tableau 'final_nominations'
final_nominations['Movie'] = movie_names
final_nominations['Character'] = characters

In [43]:
# Afficher le tableau 'final_nominations'
final_nominations.head()

,Year,Category,Nominee,Additional Info,Won,Movie,Character
0,2010,Actor -- Leading Role,Javier Bardem,Biutiful {'Uxbal'},0,Biutiful,Uxbal
1,2010,Actor -- Leading Role,Jeff Bridges,True Grit {'Rooster Cogburn'},0,True Grit,Rooster Cogburn
2,2010,Actor -- Leading Role,Jesse Eisenberg,The Social Network {'Mark Zuckerberg'},0,The Social Network,Mark Zuckerberg
3,2010,Actor -- Leading Role,Colin Firth,The King's Speech {'King George VI'},1,The King's Speech,King George VI
4,2010,Actor -- Leading Role,James Franco,127 Hours {'Aron Ralston'},0,127 Hours,Aron Ralston

In [44]:
# Supprimer la colonne 'Additional Info' car on a splité les infos 
final_nominations.drop(['Additional Info'], axis=1, inplace=True)
final_nominations.head()

,Year,Category,Nominee,Won,Movie,Character
0,2010,Actor -- Leading Role,Javier Bardem,0,Biutiful,Uxbal
1,2010,Actor -- Leading Role,Jeff Bridges,0,True Grit,Rooster Cogburn
2,2010,Actor -- Leading Role,Jesse Eisenberg,0,The Social Network,Mark Zuckerberg
3,2010,Actor -- Leading Role,Colin Firth,1,The King's Speech,King George VI
4,2010,Actor -- Leading Role,James Franco,0,127 Hours,Aron Ralston

## Exporter vers SQLite sur DB Browser

In [45]:
# méthode : to_sql(name, connexion)

In [46]:
final_nominations.dtypes

Year          int64
Category     object
Nominee      object
Won           int64
Movie        object
Character    object
dtype: object

In [47]:
# Créer une nouvelle base de données et s'y connecter
connexion = sqlite3.connect('nominations.db')

In [ ]:
final_nominations.to_sql('nominations', connexion, index=False)

In [ ]:
# Méthode : if_exists='append' = permet d'ajouter les mêmes valeurs